/**
 * Content Proposals Hook
 * 
 * Manages content proposals generated by the AI agent.
 * These are pending approval from the user (human-in-the-loop).
 */

import { useState, useEffect, useCallback } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '../lib/supabaseClient';
import { findNextAvailableDate, parseLocalDate, toCalendarTimestamp } from '../utils/calendar';
import type { ContentProposal, FactCheckStatus } from '../services/contentAgent';

interface ContentProposalDB {
	id: string;
	project_id: string;
	cluster_name: string;
	cluster_keywords: string[];
	primary_keyword?: string;
	search_volume?: number;
	difficulty?: number;
	title: string;
	slug: string;
	body: string;
	seo_score: number;
	readability_score: number;
	status: 'pending' | 'approved' | 'rejected' | 'modified' | 'archived';
	generated_at: string;
	scheduled_date?: string;
	metadata: Record<string, unknown>;
}

/**
 * Get all content proposals for a project (or all projects if projectId is undefined)
 */
export const useContentProposals = (
	projectId: string | undefined,
	options?: { enabled?: boolean },
) => {
	return useQuery({
		queryKey: ['content-proposals', projectId || 'all'],
		enabled: options?.enabled !== false,
		queryFn: async () => {
			const {
				data: { user },
			} = await supabase.auth.getUser();

			if (!user) return [];

			// `body` stays: proposal pages and the calendar preview render it.
			let query = supabase
				.from('content_proposals')
				.select('*')
				.order('generated_at', { ascending: false })
				.limit(300);

			if (projectId) {
				query = query.eq('project_id', projectId);
			} else {
				// Get all projects for user, then filter proposals
				const { data: projects } = await supabase
					.from('projects')
					.select('id')
					.eq('user_id', user.id);

				if (projects && projects.length > 0) {
					const projectIds = projects.map((p) => p.id);
					query = query.in('project_id', projectIds);
				} else {
					return [];
				}
			}

			const { data, error } = await query;

			if (error) {
				// Check if table doesn't exist (404 or 42P01)
				if (error.code === '42P01' || error.message?.includes('does not exist') || error.message?.includes('404')) {
					console.error('Table content_proposals does not exist. Please run database migrations.');
					// Return empty array instead of throwing to prevent UI breakage
					return [];
				}
				throw error;
			}

			return (data || []).map((p: ContentProposalDB) => {
				try {
					return {
						id: p.id,
						projectId: p.project_id,
						clusterName: p.cluster_name || '',
						clusterKeywords: Array.isArray(p.cluster_keywords) ? p.cluster_keywords : [],
						primaryKeyword: p.primary_keyword || (Array.isArray(p.cluster_keywords) && p.cluster_keywords.length > 0 ? p.cluster_keywords[0] : '') || p.cluster_name || '',
						searchVolume: p.search_volume,
						difficulty: p.difficulty,
						title: p.title || '',
						slug: p.slug || '',
						body: p.body || '',
						seoScore: p.seo_score || 0,
						readabilityScore: p.readability_score || 0,
						status: p.status || 'pending',
						generatedAt: p.generated_at || new Date().toISOString(),
						scheduledDate: p.scheduled_date,
						metadata: p.metadata || {},
					} as ContentProposal;
				} catch (error) {
					console.error('Error mapping proposal:', p.id, error);
					return null;
				}
			}).filter((p): p is ContentProposal => p !== null) as ContentProposal[];
		},
	});
};

/**
 * Save a content proposal (upsert - insert or update if exists)
 */
export const useSaveContentProposal = () => {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async (proposal: ContentProposal) => {
			// Use upsert to support both insert and update
			const { data, error } = await supabase
				.from('content_proposals')
				.upsert({
					id: proposal.id,
					project_id: proposal.projectId,
					cluster_name: proposal.clusterName,
					cluster_keywords: proposal.clusterKeywords,
					primary_keyword: proposal.primaryKeyword,
					search_volume: proposal.searchVolume,
					difficulty: proposal.difficulty,
					title: proposal.title,
					slug: proposal.slug,
					body: proposal.body,
					seo_score: proposal.seoScore,
					readability_score: proposal.readabilityScore,
					status: proposal.status,
					generated_at: proposal.generatedAt,
					scheduled_date: proposal.scheduledDate,
					metadata: proposal.metadata,
				}, {
					onConflict: 'id',
				})
				.select()
				.single();

			if (error) throw error;
			return data;
		},
		onSuccess: (_, proposal) => {
			queryClient.invalidateQueries({ queryKey: ['content-proposals', proposal.projectId] });
			queryClient.invalidateQueries({ queryKey: ['content-proposals', 'all'] });
		},
	});
};

// Cache for recently scheduled dates in the current session
// This ensures that when approving multiple proposals, each gets a different date
const recentlyScheduledDates = new Map<string, Set<string>>();

/**
 * Approve a content proposal (adds to calendar, content will be generated later with "Genera Ora")
 */
export const useApproveContentProposal = () => {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async ({ proposalId, projectId, modifications, autoSchedule = true }: { 
			proposalId: string; 
			projectId: string;
			modifications?: { title?: string; body?: string };
			autoSchedule?: boolean; // Auto-add to calendar
		}) => {
			// Get the proposal
			const { data: proposal, error: fetchError } = await supabase
				.from('content_proposals')
				.select('*')
				.eq('id', proposalId)
				.single();

			if (fetchError || !proposal) throw fetchError || new Error('Proposal not found');

			// Find next available date in calendar if auto-scheduling
			let scheduledDate: string | undefined;
			if (autoSchedule) {
				// Get all existing scheduled content dates (from both content and approved proposals)
				const { data: existingContent } = await supabase
					.from('content')
					.select('published_date')
					.eq('project_id', projectId)
					.not('published_date', 'is', null);

				const { data: existingProposals } = await supabase
					.from('content_proposals')
					.select('scheduled_date')
					.eq('project_id', projectId)
					.eq('status', 'approved')
					.not('scheduled_date', 'is', null);

				// Get recently scheduled dates for this project (from current session)
				const recentDates = recentlyScheduledDates.get(projectId) || new Set<string>();

				const existingDates = [
					...(existingContent || []).map((c) => c.published_date ? parseLocalDate(c.published_date) : null),
					...(existingProposals || []).map((p) => p.scheduled_date ? parseLocalDate(p.scheduled_date) : null),
					// Include recently scheduled dates from current session
					...Array.from(recentDates).map((dateStr) => parseLocalDate(dateStr)),
				].filter((d): d is Date => d !== null && !isNaN(d.getTime()));

				const nextDate = findNextAvailableDate(existingDates, 1); // 1 item per day
				// scheduled_date is TIMESTAMPTZ: write local noon so the calendar day survives any timezone
				scheduledDate = toCalendarTimestamp(nextDate);

				// Add to recently scheduled dates cache
				if (!recentlyScheduledDates.has(projectId)) {
					recentlyScheduledDates.set(projectId, new Set());
				}
				recentlyScheduledDates.get(projectId)!.add(scheduledDate);

				// Clean up cache after 5 seconds (enough time for the database to update)
				setTimeout(() => {
					const projectDates = recentlyScheduledDates.get(projectId);
					if (projectDates && scheduledDate) {
						projectDates.delete(scheduledDate);
						if (projectDates.size === 0) {
							recentlyScheduledDates.delete(projectId);
						}
					}
				}, 5000);
			}

			// Update proposal status to approved with scheduled date (don't create content yet)
			const { error: updateError } = await supabase
				.from('content_proposals')
				.update({ 
					status: modifications ? 'modified' : 'approved',
					scheduled_date: scheduledDate,
					metadata: {
						...proposal.metadata,
						approved_at: new Date().toISOString(),
						scheduled_date: scheduledDate,
						...(modifications ? { modifications } : {}),
					},
				})
				.eq('id', proposalId);

			if (updateError) throw updateError;

			return { scheduledDate };
		},
		onSuccess: (_, variables) => {
			queryClient.invalidateQueries({ queryKey: ['content-proposals', variables.projectId] });
			queryClient.invalidateQueries({ queryKey: ['content-proposals', 'all'] });
		},
	});
};

/**
 * Update scheduled date for an approved proposal
 */
export const useUpdateProposalScheduledDate = () => {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async ({ proposalId, scheduledDate }: {
			proposalId: string;
			projectId: string;
			scheduledDate: string | null; // null to remove from calendar
		}) => {
			const { error } = await supabase
				.from('content_proposals')
				.update({ 
					scheduled_date: scheduledDate,
				})
				.eq('id', proposalId);

			if (error) throw error;
		},
		onSuccess: (_, variables) => {
			queryClient.invalidateQueries({ queryKey: ['content-proposals', variables.projectId] });
			queryClient.invalidateQueries({ queryKey: ['content-proposals', 'all'] });
		},
	});
};

/**
 * Reject a content proposal (archives it, won't appear in calendar)
 */
export const useRejectContentProposal = () => {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async ({ proposalId, archive = false }: {
			proposalId: string;
			projectId: string;
			archive?: boolean; // Archive instead of reject (UI-friendly)
		}) => {
			// Merge into the existing metadata — replacing it would drop serpAnalysis, refresh flags, etc.
			const { data: existing, error: fetchError } = await supabase
				.from('content_proposals')
				.select('metadata')
				.eq('id', proposalId)
				.single();
			if (fetchError) throw fetchError;
			const existingMetadata =
				existing?.metadata && typeof existing.metadata === 'object' ? (existing.metadata as Record<string, unknown>) : {};

			const { error } = await supabase
				.from('content_proposals')
				.update({ 
					status: archive ? 'archived' : 'rejected',
					scheduled_date: null, // Remove scheduled date so it doesn't appear in calendar
					metadata: {
						...existingMetadata,
						[archive ? 'archived_at' : 'rejected_at']: new Date().toISOString(),
					},
				})
				.eq('id', proposalId);

			if (error) throw error;
		},
		onSuccess: (_, variables) => {
			queryClient.invalidateQueries({ queryKey: ['content-proposals', variables.projectId] });
			queryClient.invalidateQueries({ queryKey: ['content-proposals', 'all'] });
		},
	});
};

/**
 * Generate content from an approved proposal (creates content entry in content table)
 * Now generates full content using contentAgent
 * Also handles content refresh proposals (from Content Updates)
 */
export const useGenerateContentFromProposal = () => {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async ({ proposalId, projectId }: { 
			proposalId: string; 
			projectId: string;
		}) => {
			// Get the approved proposal
			const { data: proposal, error: fetchError } = await supabase
				.from('content_proposals')
				.select('*')
				.eq('id', proposalId)
				.eq('status', 'approved')
				.single();

			if (fetchError || !proposal) {
				throw new Error('Proposal not found or not approved');
			}

			// Check if this is a content refresh proposal
			const isContentRefresh = (proposal.metadata as Record<string, unknown>)?.['isContentRefresh'] === true;
			console.log('Generating content, isContentRefresh:', isContentRefresh);

			// Check if content already exists for this proposal
			const { data: existingContent } = await supabase
				.from('content')
				.select('id')
				.eq('project_id', projectId)
				.contains('metadata', { from_proposal: proposalId })
				.limit(1);

			if (existingContent && existingContent.length > 0) {
				// Content already exists, return it
				const { data: content } = await supabase
					.from('content')
					.select('*')
					.eq('id', existingContent[0]?.id)
					.single();
				return { content, isNew: false };
			}

			// Get project data
			const { data: project, error: projectError } = await supabase
				.from('projects')
				.select('*')
				.eq('id', projectId)
				.single();

			if (projectError || !project) {
				throw new Error('Project not found');
			}

			// Check if sitemap is saved for internal linking
			// If not and website_url exists, try to fetch it
			const projectMetadata = project.metadata as Record<string, unknown> | null;
			const hasSitemapPages = projectMetadata?.['sitemap_pages'] && Array.isArray(projectMetadata['sitemap_pages']);
			
			if (project.website_url && !hasSitemapPages) {
				console.log('📄 No sitemap pages cached, fetching for internal linking...');
				try {
					const { saveSitemapToProject } = await import('../services/sitemapAnalyzer');
					const result = await saveSitemapToProject(project.id, project.website_url);
					if (result.success) {
						console.log(`✅ Cached ${result.pagesCount} sitemap pages for internal linking`);
					}
				} catch (sitemapError) {
					console.warn('⚠️ Could not fetch sitemap, continuing without external links:', sitemapError);
				}
			}

			// Generate content using contentAgent
			const { contentAgent } = await import('../services/contentAgent');
			const proposalData: ContentProposal = {
				id: proposal.id,
				projectId: proposal.project_id,
				clusterName: proposal.cluster_name,
				clusterKeywords: Array.isArray(proposal.cluster_keywords) ? proposal.cluster_keywords : [],
				primaryKeyword: proposal.primary_keyword || proposal.cluster_keywords[0] || '',
				searchVolume: proposal.search_volume,
				difficulty: proposal.difficulty,
				title: proposal.title,
				slug: proposal.slug,
				body: proposal.body || '',
				seoScore: proposal.seo_score || 0,
				readabilityScore: proposal.readability_score || 0,
				status: proposal.status as ContentProposal['status'],
				generatedAt: proposal.generated_at,
				scheduledDate: proposal.scheduled_date,
				metadata: proposal.metadata || {},
			};

			let fullContent: string;
			// Real fact-check outcome reported by the agent: fact_checked is true only if the check ran fully.
			const factCheck: { status: FactCheckStatus | null } = { status: null };
			const onFactCheck = (status: FactCheckStatus) => { factCheck.status = status; };

			if (isContentRefresh) {
				// Use content refresh generation
				console.log('Generating content refresh...');
				fullContent = await contentAgent.generateRefreshContent(
					proposalData,
					project as any,
					(status) => {
						console.log('Content refresh progress:', status);
					},
					onFactCheck
				);
			} else {
				// Generate new content
				console.log('Generating new content...');
				fullContent = await contentAgent.generateFullContent(
					proposalData,
					project as any,
					(status) => {
						console.log('Content generation progress:', status);
					},
					onFactCheck
				);
			}

			const factChecked = factCheck.status?.ok === true;
			const factCheckMeta = {
				fact_checked: factChecked,
				...(factChecked ? {} : { fact_check_warning: factCheck.status?.warning ?? 'Fact-check did not run' }),
			};

			// Calculate scores for generated content
			const { calculateSEOScore, calculateReadability } = await import('../utils/seo');
			const seoScore = calculateSEOScore(fullContent, proposalData.primaryKeyword);
			const readabilityScore = calculateReadability(fullContent);

			// Clean the title (remove refresh emoji if present)
			const cleanTitle = proposal.title.replace(/^🔄\s*/, '');

			// If this is a content refresh and we have an original content ID, update that content
			const originalContentId = (proposal.metadata as Record<string, unknown>)?.['originalContentId'] as string | undefined;
			
			if (isContentRefresh && originalContentId) {
				// Update existing content instead of creating new
				const { data: content, error: contentError } = await supabase
					.from('content')
					.update({
						title: cleanTitle,
						body: fullContent,
						seo_score: seoScore,
						readability_score: readabilityScore,
						status: proposal.scheduled_date ? 'published' : 'draft',
						published_date: proposal.scheduled_date || null,
						updated_at: new Date().toISOString(),
						metadata: {
							refreshed_at: new Date().toISOString(),
							from_refresh_proposal: proposalId,
							refresh_reason: (proposal.metadata as Record<string, unknown>)?.['refreshReason'],
							original_url: (proposal.metadata as Record<string, unknown>)?.['originalUrl'],
							geo_optimized: true,
							...factCheckMeta,
						},
					})
					.eq('id', originalContentId)
					.select()
					.single();

				if (contentError) {
					console.warn('Error updating original content, creating new:', contentError);
					// Fall through to create new content
				} else {
					// Update proposal to mark as generated
					await supabase
						.from('content_proposals')
						.update({ 
							body: fullContent,
							seo_score: seoScore,
							readability_score: readabilityScore,
							metadata: {
								...proposal.metadata,
								content_id: content.id,
								generated_at: new Date().toISOString(),
								needsContentGeneration: false,
							},
						})
						.eq('id', proposalId);
					
					return { content, isNew: false };
				}
			}

			// Create new content in content table
			const { data: content, error: contentError } = await supabase
				.from('content')
				.insert({
					project_id: projectId,
					title: cleanTitle,
					slug: proposal.slug,
					body: fullContent,
					seo_score: seoScore,
					readability_score: readabilityScore,
					status: proposal.scheduled_date ? 'published' : 'draft',
					published_date: proposal.scheduled_date || null,
					topic: proposal.cluster_name,
					keywords_used: proposal.cluster_keywords,
					metadata: {
						...proposal.metadata,
						generated_at: new Date().toISOString(),
						from_proposal: proposalId,
						primary_keyword: proposal.primary_keyword,
						search_volume: proposal.search_volume,
						geo_optimized: true,
						...factCheckMeta,
					},
				})
				.select()
				.single();

			if (contentError) throw contentError;

			// Update proposal with generated content and scores
			const { error: updateError } = await supabase
				.from('content_proposals')
				.update({ 
					body: fullContent,
					seo_score: seoScore,
					readability_score: readabilityScore,
					metadata: {
						...proposal.metadata,
						content_id: content.id,
						generated_at: new Date().toISOString(),
						needsContentGeneration: false,
					},
				})
				.eq('id', proposalId);

			if (updateError) {
				console.warn('Error updating proposal metadata:', updateError);
				// Don't throw, content was created successfully
			}

			return { content, isNew: true };
		},
		onSuccess: (_, variables) => {
			queryClient.invalidateQueries({ queryKey: ['content-proposals', variables.projectId] });
			queryClient.invalidateQueries({ queryKey: ['content-proposals', 'all'] });
			queryClient.invalidateQueries({ queryKey: ['content', variables.projectId] });
			queryClient.invalidateQueries({ queryKey: ['content', 'all'] });
		},
	});
};

/**
 * Hook to manage content proposals with local state
 */
export const useContentProposalsState = (projectId: string | undefined) => {
	const { data: proposals } = useContentProposals(projectId);
	const [localProposals, setLocalProposals] = useState<ContentProposal[]>([]);

	useEffect(() => {
		if (proposals) {
			setLocalProposals(proposals);
		}
	}, [proposals]);

	const addProposal = useCallback((proposal: ContentProposal) => {
		setLocalProposals((prev) => [proposal, ...prev]);
	}, []);

	const removeProposal = useCallback((proposalId: string) => {
		setLocalProposals((prev) => prev.filter((p) => p.id !== proposalId));
	}, []);

	return {
		proposals: localProposals.length > 0 ? localProposals : (proposals || []),
		addProposal,
		removeProposal,
	};
};

