/**
 * Content Proposals Page
 * 
 * Shows all content proposals generated by the AI agent
 * awaiting user approval (human-in-the-loop)
 */

import { useNavigate } from '@tanstack/react-router';
import { useTranslation } from 'react-i18next';
import { Sidebar } from '../components/layout/Sidebar';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { LoadingSpinner } from '../components/ui/LoadingSpinner';
import { useContentProposals } from '../hooks/useContentProposals';
import { useApproveContentProposal, useRejectContentProposal } from '../hooks/useContentProposals';
import { EmptyState } from '../components/ui/EmptyState';
import { motion } from 'framer-motion';
import type { ContentProposal } from '../services/contentAgent';

export const ContentProposalsPage = () => {
	const { t } = useTranslation();
	const navigate = useNavigate();
	const { data: proposals, isLoading } = useContentProposals(undefined);
	const approveProposal = useApproveContentProposal();
	const rejectProposal = useRejectContentProposal();

	const pendingProposals = proposals?.filter((p) => p.status === 'pending') || [];

	const handleApprove = async (proposal: ContentProposal) => {
		try {
			await approveProposal.mutateAsync({
				proposalId: proposal.id,
				projectId: proposal.projectId,
			});
			// Navigate to the approved content
			// The content will be in the content library
		} catch (error) {
			console.error('Error approving proposal:', error);
		}
	};

	const handleReject = async (proposal: ContentProposal) => {
		try {
			await rejectProposal.mutateAsync({
				proposalId: proposal.id,
				projectId: proposal.projectId,
			});
		} catch (error) {
			console.error('Error rejecting proposal:', error);
		}
	};

	if (isLoading) {
		return (
			<div className="flex min-h-screen bg-gray-50">
				<Sidebar />
				<div className="flex-1 flex items-center justify-center">
					<LoadingSpinner size="lg" text={t('contentProposalsPage.loading')} />
				</div>
			</div>
		);
	}

	return (
		<div className="flex min-h-screen bg-gray-50">
			<Sidebar />
			<div className="flex-1">
				<div className="max-w-7xl mx-auto px-6 py-8">
					{/* Header */}
					<div className="mb-8">
						<h1 className="text-3xl font-bold text-gray-900 mb-2">{t('contentProposalsPage.title')}</h1>
						<p className="text-gray-500">
							{t('contentProposalsPage.subtitle', { count: pendingProposals.length })}
						</p>
					</div>

					{/* Proposals List */}
					{pendingProposals.length === 0 ? (
						<EmptyState
							icon="✨"
							title={t('contentProposalsPage.emptyTitle')}
							description={[
								t('contentProposalsPage.emptyDesc1'),
								t('contentProposalsPage.emptyDesc2'),
							]}
							primaryAction={{
								label: t('contentProposalsPage.goToProjects'),
								onClick: () => navigate({ to: '/projects' as any }),
								icon: '📁',
							}}
						/>
					) : (
						<div className="space-y-4">
							{pendingProposals.map((proposal, index) => (
								<motion.div
									key={proposal.id}
									initial={{ opacity: 0, y: 20 }}
									animate={{ opacity: 1, y: 0 }}
									transition={{ delay: index * 0.1 }}
								>
									<Card className="hover:border-cosmic-cyan/40 transition-all">
										<div className="flex items-start justify-between gap-6">
											<div className="flex-1">
												<div className="flex items-center gap-3 mb-3">
													<h3 className="text-xl font-bold text-gray-900">{proposal.title}</h3>
													<span className="px-2 py-1 bg-cosmic-purple/20 text-cosmic-purple text-xs rounded-full font-semibold">
														{proposal.clusterName}
													</span>
												</div>
												<p className="text-sm text-gray-600 mb-4 line-clamp-2">
													{proposal.body.substring(0, 200)}...
												</p>
												<div className="flex items-center gap-6 text-sm">
													<div className="flex items-center gap-2">
														<span className="text-gray-500">{t('contentProposalsPage.seoScoreLabel')}</span>
														<span className="font-semibold text-cosmic-cyan">{proposal.seoScore}/100</span>
													</div>
													<div className="flex items-center gap-2">
														<span className="text-gray-500">{t('contentProposalsPage.readabilityLabel')}</span>
														<span className="font-semibold text-cosmic-green">{proposal.readabilityScore}/100</span>
													</div>
													<div className="flex items-center gap-2">
														<span className="text-gray-500">{t('contentProposalsPage.keywordsLabel')}</span>
														<span className="text-gray-900">
															{proposal.clusterKeywords.slice(0, 3).join(', ')}
															{proposal.clusterKeywords.length > 3 && '...'}
														</span>
													</div>
												</div>
											</div>
											<div className="flex flex-col gap-2">
												<Button
													onClick={() => navigate({ to: `/content/${proposal.id}?proposal=true` as any })}
													variant="secondary"
													size="sm"
												>
													{t('contentProposalsPage.preview')}
												</Button>
												<Button
													onClick={() => handleApprove(proposal)}
													variant="primary"
													size="sm"
													disabled={approveProposal.isPending}
												>
													{approveProposal.isPending ? t('contentProposalsPage.approving') : t('contentProposalsPage.approve')}
												</Button>
												<Button
													onClick={() => handleReject(proposal)}
													variant="danger"
													size="sm"
													disabled={rejectProposal.isPending}
												>
													{t('contentProposalsPage.reject')}
												</Button>
											</div>
										</div>
									</Card>
								</motion.div>
							))}
						</div>
					)}
				</div>
			</div>
		</div>
	);
};

