/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisibilityRouteImport } from './routes/visibility'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SiteExplorerRouteImport } from './routes/site-explorer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PianoRouteImport } from './routes/piano'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as KeywordResearchRouteImport } from './routes/keyword-research'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentUpdatesRouteImport } from './routes/content-updates'
import { Route as CommandRouteImport } from './routes/command'
import { Route as BulkAnalysisRouteImport } from './routes/bulk-analysis'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisibilityIndexRouteImport } from './routes/visibility.index'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ItIndexRouteImport } from './routes/it.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as VisibilityProjectIdRouteImport } from './routes/visibility.$projectId'
import { Route as ReportsPortfolioRouteImport } from './routes/reports.portfolio'
import { Route as ReportsPortalRouteImport } from './routes/reports.portal'
import { Route as RankingsProjectIdRouteImport } from './routes/rankings.$projectId'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OauthMcpAuthorizeRouteImport } from './routes/oauth.mcp-authorize'
import { Route as ItSignupRouteImport } from './routes/it.signup'
import { Route as ItResetPasswordRouteImport } from './routes/it.reset-password'
import { Route as ItLoginRouteImport } from './routes/it.login'
import { Route as ItHelpRouteImport } from './routes/it.help'
import { Route as ItForgotPasswordRouteImport } from './routes/it.forgot-password'
import { Route as DocsMcpRouteImport } from './routes/docs.mcp'
import { Route as ContentNewRouteImport } from './routes/content.new'
import { Route as ContentGenerateRouteImport } from './routes/content.generate'
import { Route as ContentContentIdRouteImport } from './routes/content.$contentId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AgentProjectIdRouteImport } from './routes/agent.$projectId'
import { Route as VisibilityProjectIdIndexRouteImport } from './routes/visibility.$projectId.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as VisibilityProjectIdSettingsRouteImport } from './routes/visibility.$projectId.settings'
import { Route as VisibilityProjectIdRunsRouteImport } from './routes/visibility.$projectId.runs'
import { Route as VisibilityProjectIdRankingsRouteImport } from './routes/visibility.$projectId.rankings'
import { Route as VisibilityProjectIdQueriesRouteImport } from './routes/visibility.$projectId.queries'
import { Route as VisibilityProjectIdPlaybookRouteImport } from './routes/visibility.$projectId.playbook'
import { Route as VisibilityProjectIdInsightsRouteImport } from './routes/visibility.$projectId.insights'
import { Route as VisibilityProjectIdCompetitorsRouteImport } from './routes/visibility.$projectId.competitors'
import { Route as VisibilityProjectIdCitationsRouteImport } from './routes/visibility.$projectId.citations'
import { Route as ReportsPortalReportIdRouteImport } from './routes/reports.portal.$reportId'
import { Route as ItDocsMcpRouteImport } from './routes/it.docs.mcp'

const VisibilityRoute = VisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteExplorerRoute = SiteExplorerRouteImport.update({
  id: '/site-explorer',
  path: '/site-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoRoute = PianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordResearchRoute = KeywordResearchRouteImport.update({
  id: '/keyword-research',
  path: '/keyword-research',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentUpdatesRoute = ContentUpdatesRouteImport.update({
  id: '/content-updates',
  path: '/content-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkAnalysisRoute = BulkAnalysisRouteImport.update({
  id: '/bulk-analysis',
  path: '/bulk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisibilityIndexRoute = VisibilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisibilityRoute,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItIndexRoute = ItIndexRouteImport.update({
  id: '/it/',
  path: '/it/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisibilityProjectIdRoute = VisibilityProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => VisibilityRoute,
} as any)
const ReportsPortfolioRoute = ReportsPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsPortalRoute = ReportsPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ReportsRoute,
} as any)
const RankingsProjectIdRoute = RankingsProjectIdRouteImport.update({
  id: '/rankings/$projectId',
  path: '/rankings/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMcpAuthorizeRoute = OauthMcpAuthorizeRouteImport.update({
  id: '/oauth/mcp-authorize',
  path: '/oauth/mcp-authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSignupRoute = ItSignupRouteImport.update({
  id: '/it/signup',
  path: '/it/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ItResetPasswordRoute = ItResetPasswordRouteImport.update({
  id: '/it/reset-password',
  path: '/it/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ItLoginRoute = ItLoginRouteImport.update({
  id: '/it/login',
  path: '/it/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItHelpRoute = ItHelpRouteImport.update({
  id: '/it/help',
  path: '/it/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ItForgotPasswordRoute = ItForgotPasswordRouteImport.update({
  id: '/it/forgot-password',
  path: '/it/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/docs/mcp',
  path: '/docs/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNewRoute = ContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentGenerateRoute = ContentGenerateRouteImport.update({
  id: '/content/generate',
  path: '/content/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/content/$contentId',
  path: '/content/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProjectIdRoute = AgentProjectIdRouteImport.update({
  id: '/agent/$projectId',
  path: '/agent/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const VisibilityProjectIdIndexRoute =
  VisibilityProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const VisibilityProjectIdSettingsRoute =
  VisibilityProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const VisibilityProjectIdRunsRoute = VisibilityProjectIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => VisibilityProjectIdRoute,
} as any)
const VisibilityProjectIdRankingsRoute =
  VisibilityProjectIdRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const VisibilityProjectIdQueriesRoute =
  VisibilityProjectIdQueriesRouteImport.update({
    id: '/queries',
    path: '/queries',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const VisibilityProjectIdPlaybookRoute =
  VisibilityProjectIdPlaybookRouteImport.update({
    id: '/playbook',
    path: '/playbook',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const VisibilityProjectIdInsightsRoute =
  VisibilityProjectIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const VisibilityProjectIdCompetitorsRoute =
  VisibilityProjectIdCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const VisibilityProjectIdCitationsRoute =
  VisibilityProjectIdCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => VisibilityProjectIdRoute,
  } as any)
const ReportsPortalReportIdRoute = ReportsPortalReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsPortalRoute,
} as any)
const ItDocsMcpRoute = ItDocsMcpRouteImport.update({
  id: '/it/docs/mcp',
  path: '/it/docs/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/bulk-analysis': typeof BulkAnalysisRoute
  '/command': typeof CommandRoute
  '/content-updates': typeof ContentUpdatesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/keyword-research': typeof KeywordResearchRoute
  '/keywords': typeof KeywordsRoute
  '/login': typeof LoginRoute
  '/piano': typeof PianoRoute
  '/pricing': typeof PricingRoute
  '/proposals': typeof ProposalsRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-explorer': typeof SiteExplorerRoute
  '/upgrade': typeof UpgradeRoute
  '/visibility': typeof VisibilityRouteWithChildren
  '/agent/$projectId': typeof AgentProjectIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/content/generate': typeof ContentGenerateRoute
  '/content/new': typeof ContentNewRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/it/forgot-password': typeof ItForgotPasswordRoute
  '/it/help': typeof ItHelpRoute
  '/it/login': typeof ItLoginRoute
  '/it/reset-password': typeof ItResetPasswordRoute
  '/it/signup': typeof ItSignupRoute
  '/oauth/mcp-authorize': typeof OauthMcpAuthorizeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/r/$token': typeof RTokenRoute
  '/rankings/$projectId': typeof RankingsProjectIdRoute
  '/reports/portal': typeof ReportsPortalRouteWithChildren
  '/reports/portfolio': typeof ReportsPortfolioRoute
  '/visibility/$projectId': typeof VisibilityProjectIdRouteWithChildren
  '/agent': typeof AgentIndexRoute
  '/it': typeof ItIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/visibility/': typeof VisibilityIndexRoute
  '/it/docs/mcp': typeof ItDocsMcpRoute
  '/reports/portal/$reportId': typeof ReportsPortalReportIdRoute
  '/visibility/$projectId/citations': typeof VisibilityProjectIdCitationsRoute
  '/visibility/$projectId/competitors': typeof VisibilityProjectIdCompetitorsRoute
  '/visibility/$projectId/insights': typeof VisibilityProjectIdInsightsRoute
  '/visibility/$projectId/playbook': typeof VisibilityProjectIdPlaybookRoute
  '/visibility/$projectId/queries': typeof VisibilityProjectIdQueriesRoute
  '/visibility/$projectId/rankings': typeof VisibilityProjectIdRankingsRoute
  '/visibility/$projectId/runs': typeof VisibilityProjectIdRunsRoute
  '/visibility/$projectId/settings': typeof VisibilityProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/visibility/$projectId/': typeof VisibilityProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/bulk-analysis': typeof BulkAnalysisRoute
  '/command': typeof CommandRoute
  '/content-updates': typeof ContentUpdatesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/keyword-research': typeof KeywordResearchRoute
  '/keywords': typeof KeywordsRoute
  '/login': typeof LoginRoute
  '/piano': typeof PianoRoute
  '/pricing': typeof PricingRoute
  '/proposals': typeof ProposalsRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-explorer': typeof SiteExplorerRoute
  '/upgrade': typeof UpgradeRoute
  '/agent/$projectId': typeof AgentProjectIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/content/generate': typeof ContentGenerateRoute
  '/content/new': typeof ContentNewRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/it/forgot-password': typeof ItForgotPasswordRoute
  '/it/help': typeof ItHelpRoute
  '/it/login': typeof ItLoginRoute
  '/it/reset-password': typeof ItResetPasswordRoute
  '/it/signup': typeof ItSignupRoute
  '/oauth/mcp-authorize': typeof OauthMcpAuthorizeRoute
  '/projects/new': typeof ProjectsNewRoute
  '/r/$token': typeof RTokenRoute
  '/rankings/$projectId': typeof RankingsProjectIdRoute
  '/reports/portal': typeof ReportsPortalRouteWithChildren
  '/reports/portfolio': typeof ReportsPortfolioRoute
  '/agent': typeof AgentIndexRoute
  '/it': typeof ItIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/visibility': typeof VisibilityIndexRoute
  '/it/docs/mcp': typeof ItDocsMcpRoute
  '/reports/portal/$reportId': typeof ReportsPortalReportIdRoute
  '/visibility/$projectId/citations': typeof VisibilityProjectIdCitationsRoute
  '/visibility/$projectId/competitors': typeof VisibilityProjectIdCompetitorsRoute
  '/visibility/$projectId/insights': typeof VisibilityProjectIdInsightsRoute
  '/visibility/$projectId/playbook': typeof VisibilityProjectIdPlaybookRoute
  '/visibility/$projectId/queries': typeof VisibilityProjectIdQueriesRoute
  '/visibility/$projectId/rankings': typeof VisibilityProjectIdRankingsRoute
  '/visibility/$projectId/runs': typeof VisibilityProjectIdRunsRoute
  '/visibility/$projectId/settings': typeof VisibilityProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/visibility/$projectId': typeof VisibilityProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/bulk-analysis': typeof BulkAnalysisRoute
  '/command': typeof CommandRoute
  '/content-updates': typeof ContentUpdatesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/keyword-research': typeof KeywordResearchRoute
  '/keywords': typeof KeywordsRoute
  '/login': typeof LoginRoute
  '/piano': typeof PianoRoute
  '/pricing': typeof PricingRoute
  '/proposals': typeof ProposalsRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site-explorer': typeof SiteExplorerRoute
  '/upgrade': typeof UpgradeRoute
  '/visibility': typeof VisibilityRouteWithChildren
  '/agent/$projectId': typeof AgentProjectIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/content/generate': typeof ContentGenerateRoute
  '/content/new': typeof ContentNewRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/it/forgot-password': typeof ItForgotPasswordRoute
  '/it/help': typeof ItHelpRoute
  '/it/login': typeof ItLoginRoute
  '/it/reset-password': typeof ItResetPasswordRoute
  '/it/signup': typeof ItSignupRoute
  '/oauth/mcp-authorize': typeof OauthMcpAuthorizeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/r/$token': typeof RTokenRoute
  '/rankings/$projectId': typeof RankingsProjectIdRoute
  '/reports/portal': typeof ReportsPortalRouteWithChildren
  '/reports/portfolio': typeof ReportsPortfolioRoute
  '/visibility/$projectId': typeof VisibilityProjectIdRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/it/': typeof ItIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/visibility/': typeof VisibilityIndexRoute
  '/it/docs/mcp': typeof ItDocsMcpRoute
  '/reports/portal/$reportId': typeof ReportsPortalReportIdRoute
  '/visibility/$projectId/citations': typeof VisibilityProjectIdCitationsRoute
  '/visibility/$projectId/competitors': typeof VisibilityProjectIdCompetitorsRoute
  '/visibility/$projectId/insights': typeof VisibilityProjectIdInsightsRoute
  '/visibility/$projectId/playbook': typeof VisibilityProjectIdPlaybookRoute
  '/visibility/$projectId/queries': typeof VisibilityProjectIdQueriesRoute
  '/visibility/$projectId/rankings': typeof VisibilityProjectIdRankingsRoute
  '/visibility/$projectId/runs': typeof VisibilityProjectIdRunsRoute
  '/visibility/$projectId/settings': typeof VisibilityProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/visibility/$projectId/': typeof VisibilityProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/billing'
    | '/bulk-analysis'
    | '/command'
    | '/content-updates'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/home'
    | '/keyword-research'
    | '/keywords'
    | '/login'
    | '/piano'
    | '/pricing'
    | '/proposals'
    | '/report'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/site-explorer'
    | '/upgrade'
    | '/visibility'
    | '/agent/$projectId'
    | '/auth/callback'
    | '/content/$contentId'
    | '/content/generate'
    | '/content/new'
    | '/docs/mcp'
    | '/it/forgot-password'
    | '/it/help'
    | '/it/login'
    | '/it/reset-password'
    | '/it/signup'
    | '/oauth/mcp-authorize'
    | '/projects/$projectId'
    | '/projects/new'
    | '/r/$token'
    | '/rankings/$projectId'
    | '/reports/portal'
    | '/reports/portfolio'
    | '/visibility/$projectId'
    | '/agent'
    | '/it'
    | '/projects'
    | '/rankings'
    | '/visibility/'
    | '/it/docs/mcp'
    | '/reports/portal/$reportId'
    | '/visibility/$projectId/citations'
    | '/visibility/$projectId/competitors'
    | '/visibility/$projectId/insights'
    | '/visibility/$projectId/playbook'
    | '/visibility/$projectId/queries'
    | '/visibility/$projectId/rankings'
    | '/visibility/$projectId/runs'
    | '/visibility/$projectId/settings'
    | '/projects/$projectId/'
    | '/visibility/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/billing'
    | '/bulk-analysis'
    | '/command'
    | '/content-updates'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/home'
    | '/keyword-research'
    | '/keywords'
    | '/login'
    | '/piano'
    | '/pricing'
    | '/proposals'
    | '/report'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/site-explorer'
    | '/upgrade'
    | '/agent/$projectId'
    | '/auth/callback'
    | '/content/$contentId'
    | '/content/generate'
    | '/content/new'
    | '/docs/mcp'
    | '/it/forgot-password'
    | '/it/help'
    | '/it/login'
    | '/it/reset-password'
    | '/it/signup'
    | '/oauth/mcp-authorize'
    | '/projects/new'
    | '/r/$token'
    | '/rankings/$projectId'
    | '/reports/portal'
    | '/reports/portfolio'
    | '/agent'
    | '/it'
    | '/projects'
    | '/rankings'
    | '/visibility'
    | '/it/docs/mcp'
    | '/reports/portal/$reportId'
    | '/visibility/$projectId/citations'
    | '/visibility/$projectId/competitors'
    | '/visibility/$projectId/insights'
    | '/visibility/$projectId/playbook'
    | '/visibility/$projectId/queries'
    | '/visibility/$projectId/rankings'
    | '/visibility/$projectId/runs'
    | '/visibility/$projectId/settings'
    | '/projects/$projectId'
    | '/visibility/$projectId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/billing'
    | '/bulk-analysis'
    | '/command'
    | '/content-updates'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/home'
    | '/keyword-research'
    | '/keywords'
    | '/login'
    | '/piano'
    | '/pricing'
    | '/proposals'
    | '/report'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/site-explorer'
    | '/upgrade'
    | '/visibility'
    | '/agent/$projectId'
    | '/auth/callback'
    | '/content/$contentId'
    | '/content/generate'
    | '/content/new'
    | '/docs/mcp'
    | '/it/forgot-password'
    | '/it/help'
    | '/it/login'
    | '/it/reset-password'
    | '/it/signup'
    | '/oauth/mcp-authorize'
    | '/projects/$projectId'
    | '/projects/new'
    | '/r/$token'
    | '/rankings/$projectId'
    | '/reports/portal'
    | '/reports/portfolio'
    | '/visibility/$projectId'
    | '/agent/'
    | '/it/'
    | '/projects/'
    | '/rankings/'
    | '/visibility/'
    | '/it/docs/mcp'
    | '/reports/portal/$reportId'
    | '/visibility/$projectId/citations'
    | '/visibility/$projectId/competitors'
    | '/visibility/$projectId/insights'
    | '/visibility/$projectId/playbook'
    | '/visibility/$projectId/queries'
    | '/visibility/$projectId/rankings'
    | '/visibility/$projectId/runs'
    | '/visibility/$projectId/settings'
    | '/projects/$projectId/'
    | '/visibility/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  BillingRoute: typeof BillingRoute
  BulkAnalysisRoute: typeof BulkAnalysisRoute
  CommandRoute: typeof CommandRoute
  ContentUpdatesRoute: typeof ContentUpdatesRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  KeywordResearchRoute: typeof KeywordResearchRoute
  KeywordsRoute: typeof KeywordsRoute
  LoginRoute: typeof LoginRoute
  PianoRoute: typeof PianoRoute
  PricingRoute: typeof PricingRoute
  ProposalsRoute: typeof ProposalsRoute
  ReportRoute: typeof ReportRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SiteExplorerRoute: typeof SiteExplorerRoute
  UpgradeRoute: typeof UpgradeRoute
  VisibilityRoute: typeof VisibilityRouteWithChildren
  AgentProjectIdRoute: typeof AgentProjectIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ContentContentIdRoute: typeof ContentContentIdRoute
  ContentGenerateRoute: typeof ContentGenerateRoute
  ContentNewRoute: typeof ContentNewRoute
  DocsMcpRoute: typeof DocsMcpRoute
  ItForgotPasswordRoute: typeof ItForgotPasswordRoute
  ItHelpRoute: typeof ItHelpRoute
  ItLoginRoute: typeof ItLoginRoute
  ItResetPasswordRoute: typeof ItResetPasswordRoute
  ItSignupRoute: typeof ItSignupRoute
  OauthMcpAuthorizeRoute: typeof OauthMcpAuthorizeRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  RTokenRoute: typeof RTokenRoute
  RankingsProjectIdRoute: typeof RankingsProjectIdRoute
  AgentIndexRoute: typeof AgentIndexRoute
  ItIndexRoute: typeof ItIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ItDocsMcpRoute: typeof ItDocsMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visibility': {
      id: '/visibility'
      path: '/visibility'
      fullPath: '/visibility'
      preLoaderRoute: typeof VisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-explorer': {
      id: '/site-explorer'
      path: '/site-explorer'
      fullPath: '/site-explorer'
      preLoaderRoute: typeof SiteExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano': {
      id: '/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof PianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyword-research': {
      id: '/keyword-research'
      path: '/keyword-research'
      fullPath: '/keyword-research'
      preLoaderRoute: typeof KeywordResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-updates': {
      id: '/content-updates'
      path: '/content-updates'
      fullPath: '/content-updates'
      preLoaderRoute: typeof ContentUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-analysis': {
      id: '/bulk-analysis'
      path: '/bulk-analysis'
      fullPath: '/bulk-analysis'
      preLoaderRoute: typeof BulkAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visibility/': {
      id: '/visibility/'
      path: '/'
      fullPath: '/visibility/'
      preLoaderRoute: typeof VisibilityIndexRouteImport
      parentRoute: typeof VisibilityRoute
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/': {
      id: '/it/'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visibility/$projectId': {
      id: '/visibility/$projectId'
      path: '/$projectId'
      fullPath: '/visibility/$projectId'
      preLoaderRoute: typeof VisibilityProjectIdRouteImport
      parentRoute: typeof VisibilityRoute
    }
    '/reports/portfolio': {
      id: '/reports/portfolio'
      path: '/portfolio'
      fullPath: '/reports/portfolio'
      preLoaderRoute: typeof ReportsPortfolioRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/portal': {
      id: '/reports/portal'
      path: '/portal'
      fullPath: '/reports/portal'
      preLoaderRoute: typeof ReportsPortalRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/rankings/$projectId': {
      id: '/rankings/$projectId'
      path: '/rankings/$projectId'
      fullPath: '/rankings/$projectId'
      preLoaderRoute: typeof RankingsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/mcp-authorize': {
      id: '/oauth/mcp-authorize'
      path: '/oauth/mcp-authorize'
      fullPath: '/oauth/mcp-authorize'
      preLoaderRoute: typeof OauthMcpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/signup': {
      id: '/it/signup'
      path: '/it/signup'
      fullPath: '/it/signup'
      preLoaderRoute: typeof ItSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/reset-password': {
      id: '/it/reset-password'
      path: '/it/reset-password'
      fullPath: '/it/reset-password'
      preLoaderRoute: typeof ItResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/login': {
      id: '/it/login'
      path: '/it/login'
      fullPath: '/it/login'
      preLoaderRoute: typeof ItLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/help': {
      id: '/it/help'
      path: '/it/help'
      fullPath: '/it/help'
      preLoaderRoute: typeof ItHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/forgot-password': {
      id: '/it/forgot-password'
      path: '/it/forgot-password'
      fullPath: '/it/forgot-password'
      preLoaderRoute: typeof ItForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/docs/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/new': {
      id: '/content/new'
      path: '/content/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof ContentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/generate': {
      id: '/content/generate'
      path: '/content/generate'
      fullPath: '/content/generate'
      preLoaderRoute: typeof ContentGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$projectId': {
      id: '/agent/$projectId'
      path: '/agent/$projectId'
      fullPath: '/agent/$projectId'
      preLoaderRoute: typeof AgentProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visibility/$projectId/': {
      id: '/visibility/$projectId/'
      path: '/'
      fullPath: '/visibility/$projectId/'
      preLoaderRoute: typeof VisibilityProjectIdIndexRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/visibility/$projectId/settings': {
      id: '/visibility/$projectId/settings'
      path: '/settings'
      fullPath: '/visibility/$projectId/settings'
      preLoaderRoute: typeof VisibilityProjectIdSettingsRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/runs': {
      id: '/visibility/$projectId/runs'
      path: '/runs'
      fullPath: '/visibility/$projectId/runs'
      preLoaderRoute: typeof VisibilityProjectIdRunsRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/rankings': {
      id: '/visibility/$projectId/rankings'
      path: '/rankings'
      fullPath: '/visibility/$projectId/rankings'
      preLoaderRoute: typeof VisibilityProjectIdRankingsRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/queries': {
      id: '/visibility/$projectId/queries'
      path: '/queries'
      fullPath: '/visibility/$projectId/queries'
      preLoaderRoute: typeof VisibilityProjectIdQueriesRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/playbook': {
      id: '/visibility/$projectId/playbook'
      path: '/playbook'
      fullPath: '/visibility/$projectId/playbook'
      preLoaderRoute: typeof VisibilityProjectIdPlaybookRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/insights': {
      id: '/visibility/$projectId/insights'
      path: '/insights'
      fullPath: '/visibility/$projectId/insights'
      preLoaderRoute: typeof VisibilityProjectIdInsightsRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/competitors': {
      id: '/visibility/$projectId/competitors'
      path: '/competitors'
      fullPath: '/visibility/$projectId/competitors'
      preLoaderRoute: typeof VisibilityProjectIdCompetitorsRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/visibility/$projectId/citations': {
      id: '/visibility/$projectId/citations'
      path: '/citations'
      fullPath: '/visibility/$projectId/citations'
      preLoaderRoute: typeof VisibilityProjectIdCitationsRouteImport
      parentRoute: typeof VisibilityProjectIdRoute
    }
    '/reports/portal/$reportId': {
      id: '/reports/portal/$reportId'
      path: '/$reportId'
      fullPath: '/reports/portal/$reportId'
      preLoaderRoute: typeof ReportsPortalReportIdRouteImport
      parentRoute: typeof ReportsPortalRoute
    }
    '/it/docs/mcp': {
      id: '/it/docs/mcp'
      path: '/it/docs/mcp'
      fullPath: '/it/docs/mcp'
      preLoaderRoute: typeof ItDocsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsPortalRouteChildren {
  ReportsPortalReportIdRoute: typeof ReportsPortalReportIdRoute
}

const ReportsPortalRouteChildren: ReportsPortalRouteChildren = {
  ReportsPortalReportIdRoute: ReportsPortalReportIdRoute,
}

const ReportsPortalRouteWithChildren = ReportsPortalRoute._addFileChildren(
  ReportsPortalRouteChildren,
)

interface ReportsRouteChildren {
  ReportsPortalRoute: typeof ReportsPortalRouteWithChildren
  ReportsPortfolioRoute: typeof ReportsPortfolioRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsPortalRoute: ReportsPortalRouteWithChildren,
  ReportsPortfolioRoute: ReportsPortfolioRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface VisibilityProjectIdRouteChildren {
  VisibilityProjectIdCitationsRoute: typeof VisibilityProjectIdCitationsRoute
  VisibilityProjectIdCompetitorsRoute: typeof VisibilityProjectIdCompetitorsRoute
  VisibilityProjectIdInsightsRoute: typeof VisibilityProjectIdInsightsRoute
  VisibilityProjectIdPlaybookRoute: typeof VisibilityProjectIdPlaybookRoute
  VisibilityProjectIdQueriesRoute: typeof VisibilityProjectIdQueriesRoute
  VisibilityProjectIdRankingsRoute: typeof VisibilityProjectIdRankingsRoute
  VisibilityProjectIdRunsRoute: typeof VisibilityProjectIdRunsRoute
  VisibilityProjectIdSettingsRoute: typeof VisibilityProjectIdSettingsRoute
  VisibilityProjectIdIndexRoute: typeof VisibilityProjectIdIndexRoute
}

const VisibilityProjectIdRouteChildren: VisibilityProjectIdRouteChildren = {
  VisibilityProjectIdCitationsRoute: VisibilityProjectIdCitationsRoute,
  VisibilityProjectIdCompetitorsRoute: VisibilityProjectIdCompetitorsRoute,
  VisibilityProjectIdInsightsRoute: VisibilityProjectIdInsightsRoute,
  VisibilityProjectIdPlaybookRoute: VisibilityProjectIdPlaybookRoute,
  VisibilityProjectIdQueriesRoute: VisibilityProjectIdQueriesRoute,
  VisibilityProjectIdRankingsRoute: VisibilityProjectIdRankingsRoute,
  VisibilityProjectIdRunsRoute: VisibilityProjectIdRunsRoute,
  VisibilityProjectIdSettingsRoute: VisibilityProjectIdSettingsRoute,
  VisibilityProjectIdIndexRoute: VisibilityProjectIdIndexRoute,
}

const VisibilityProjectIdRouteWithChildren =
  VisibilityProjectIdRoute._addFileChildren(VisibilityProjectIdRouteChildren)

interface VisibilityRouteChildren {
  VisibilityProjectIdRoute: typeof VisibilityProjectIdRouteWithChildren
  VisibilityIndexRoute: typeof VisibilityIndexRoute
}

const VisibilityRouteChildren: VisibilityRouteChildren = {
  VisibilityProjectIdRoute: VisibilityProjectIdRouteWithChildren,
  VisibilityIndexRoute: VisibilityIndexRoute,
}

const VisibilityRouteWithChildren = VisibilityRoute._addFileChildren(
  VisibilityRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  BillingRoute: BillingRoute,
  BulkAnalysisRoute: BulkAnalysisRoute,
  CommandRoute: CommandRoute,
  ContentUpdatesRoute: ContentUpdatesRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  KeywordResearchRoute: KeywordResearchRoute,
  KeywordsRoute: KeywordsRoute,
  LoginRoute: LoginRoute,
  PianoRoute: PianoRoute,
  PricingRoute: PricingRoute,
  ProposalsRoute: ProposalsRoute,
  ReportRoute: ReportRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SiteExplorerRoute: SiteExplorerRoute,
  UpgradeRoute: UpgradeRoute,
  VisibilityRoute: VisibilityRouteWithChildren,
  AgentProjectIdRoute: AgentProjectIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ContentContentIdRoute: ContentContentIdRoute,
  ContentGenerateRoute: ContentGenerateRoute,
  ContentNewRoute: ContentNewRoute,
  DocsMcpRoute: DocsMcpRoute,
  ItForgotPasswordRoute: ItForgotPasswordRoute,
  ItHelpRoute: ItHelpRoute,
  ItLoginRoute: ItLoginRoute,
  ItResetPasswordRoute: ItResetPasswordRoute,
  ItSignupRoute: ItSignupRoute,
  OauthMcpAuthorizeRoute: OauthMcpAuthorizeRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  RTokenRoute: RTokenRoute,
  RankingsProjectIdRoute: RankingsProjectIdRoute,
  AgentIndexRoute: AgentIndexRoute,
  ItIndexRoute: ItIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ItDocsMcpRoute: ItDocsMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
